### ISSUE TITLE
Support for Qt5

### ISSUE THREAD

**Issue by sl1pkn07** [darealshinji/delaycut#1]
Hi (and happy new year)

I try build delaycut with Qt5 framework

first i added in delaycut.pro in Qt+= 'widgets' and edit the main.cpp for change 'QtGui/QApplication' to 'QApplication' as suggested in https://forum.qt.io/topic/22882/solved-qapplication-no-such-file-or-directory

but when build i get:

http://sl1pkn07.wtf/paste/view/3846985b

any help?

i use gcc 5.3.0 and Qt5 5.5.1 on linux

greetings

**Comment by darealshinji** [comment]
It should now build with Qt4 and Qt5. Can you confirm that?

**Comment by sl1pkn07** [comment]
yes. can build ok with Qt5 and, at least, can launch without error

thanks bro!

**Comment by darealshinji** [comment]
You're welcome.
