### ISSUE TITLE
Predictable Crashes

### ISSUE THREAD

**Issue by rsaotome2k21** [darealshinji/delaycut#13]
Using Windows 10 x64 21H2, AMD 7950x.

Build tested: 1.4.3.9 (all 3)

Files tested on: EAC3 640 kbps

After processing 2x EAC3 files in a row, the program will start ramping up CPU usage, then a seconds later, it'll crash.

Could you please look into this?

**Comment by bitblaster** [comment]
Hi @rsaotome2k21, can you please provide a sample file (preferably small) which causes the crash?

**Comment by rsaotome2k21** [comment]
I've only tested AC3 & EAC3 so far, but pretty much anything will set off the crash.

Just process any ac3 or eac3 file, then process it again or another file, one of your CPU cores will then become very active, then within a short amount of time, usually less than 30 seconds, it'll crash.

But here's a small sample file from a DVD rip of an old TV show, just as an example.
[c54wau_s01e26.zip](https://github.com/darealshinji/delaycut/files/10469724/c54wau_s01e26.zip)

**Comment by bitblaster** [comment]
@rsaotome2k21: yes, this was fixed in my commits and it is already merged. But the current release is very old (2017) and doesn't include this fix

@darealshinji: can you please process a new release with the latest sources? Or guide me on how to do it?

**Comment by darealshinji** [comment]
I will create a new release

**Comment by darealshinji** [comment]
I've added some small fixes and made it compatible with Qt6. Can you test if it runs correctly?
[delaycut.zip](https://github.com/darealshinji/delaycut/files/10512987/delaycut.zip)

**Comment by bitblaster** [comment]
It works ok for me even if that's only the Windows build.
Do you have some kind of automated/dockerized build or is it a manual-only task?

@rsaotome2k21: can you please check on your side?

**Comment by rsaotome2k21** [comment]
Both builds seem to be working just fine, processed multiple audio tracks, no crashes, CPU isn't ramping up.
Much appreciated! :)

**Comment by darealshinji** [comment]
The builds were done manually using [MXE](https://github.com/mxe/mxe) on Linux.
