### ISSUE TITLE
-startdelay doesn't do anything in cli

### ISSUE THREAD

**Issue by poxitron** [darealshinji/delaycut#2]
Hi, darealshinji.

When I use this command line "delaycut.exe -startdelay 1000 -i S:[Ext
raido-Muxeado]\test.wav" the output file have the same length as the input one, but it works well using the gui.
I'm using Delaycut 1.4.3.7 and Windows 7 x64.

I've attached the logs, in case they are usefull.
[cli_log.txt](https://github.com/darealshinji/delaycut/files/76672/cli_log.txt)
[gui_log.txt](https://github.com/darealshinji/delaycut/files/76673/gui_log.txt)

**Comment by darealshinji** [comment]
I've fixed the problem. You can find the new Windows build in the
release section: https://github.com/darealshinji/delaycut/releases/tag/v1.4.3.7-1
