### ISSUE TITLE
proper version bump

### ISSUE THREAD

**Issue by Selur** [darealshinji/delaycut#3]
I agree that a version dump is necessary since, but please instead of using:

> 1.4.3.7-1

use:

> 1.4.3.8

since changing the version and the version scheme is a pain.

=> would be nice if the version could be changed to 1.4.3.8

**Comment by darealshinji** [comment]
Well, I didn't want to bump the version since I'm not the original upstream author, but I guess it's okay since nobody except for me seems to be working on this right now?

**Comment by Selur** [comment]
I'm pretty sure it's okay to bump the version and the old delaycut project seems to be abandoned for quite some time.

**Comment by darealshinji** [comment]
New release is available here: https://github.com/darealshinji/delaycut/releases/tag/v1.4.3.8

**Comment by darealshinji** [comment]
By the way, if you don't mind can you compile an OS X build that I could add to the releases?

**Comment by Selur** [comment]
Attached a build for you as an .app to include all the Qt dependencies.
[delaycut_macOS10.11.3_Qt5.5.1.zip](https://github.com/darealshinji/delaycut/files/129631/delaycut_macOS10.11.3_Qt5.5.1.zip)

**Comment by darealshinji** [comment]
I've added it to the releases. Thanks.
