### ISSUE TITLE
macOS 10.12.2 .app/.7z permission issues?

### ISSUE THREAD

**Issue by racoiaws** [darealshinji/delaycut#6]
Opening `delaycut.app` from `delaycut-1.4.3.9-mac10.12.7z` results in an error: "The application “delaycut” can’t be opened."

I was able to run the `delaycut.app/Contents/MacOS/delaycut` executable after `chmod +x delaycut.app/Contents/MacOS/delaycut`, but opening the .app still showed the error.

**Comment by darealshinji** [comment]
This is the first time someone reports that the macOS version isn't working. Unfortunately I can't help much since I don't have macOS. The macOS build was made by @Selur.

**Comment by Selur** [comment]
Sorry, on a trip in China atm. and can't access my mac atm. Will try to remember the problem and look into it at the start of November.

**Comment by JessePeden** [comment]
> Opening `delaycut.app` from `delaycut-1.4.3.9-mac10.12.7z` results in an error: "The application “delaycut” can’t be opened."
> 
> I was able to run the `delaycut.app/Contents/MacOS/delaycut` executable after `chmod +x delaycut.app/Contents/MacOS/delaycut`, but opening the .app still showed the error.

It's a little late, and you may have already figured it out but, if you just run chmod +x on the .app (just like you did for the binary inside of it) it will allow you to run the .app directly without an error.

**Comment by racoiaws** [comment]
IIRC `chmod +x` on the .app didn't work for me, that's why I dived into its contents, but that was a long time ago. Thanks anyway.

I assume 7zip strips some things and distributing the macOS app in a traditional .dmg archive instead of a .7z should do the work.

**Comment by JessePeden** [comment]
Gotcha. I only posted that last night because I ran into the issue on macOS Mojave with the 1.4.3.9 version on delaycut, and had to use chmod +x on both the .app and binary to get it working.

I didn't know there even was a Mac version until last night. I used delaycut about 10+ years ago but was the Windows version, and had just used Wineskin to run it on macOS.  Now I don't have to do that.
