### ISSUE TITLE
Crash when trying 2 cuts 

### ISSUE THREAD

**Issue by r4dius** [darealshinji/delaycut#8]
Hi, I just used the tools (win64-msvc verison) to add delay on 2 ac3 files successively but at the end of the 2nd one when the finishing popup should pop, it just crashes, not sure if the stream is finished or not (I did not check),
I have to close / reopen the app between each file

**Comment by bitblaster** [comment]
Yes, I'm also experiencing this with ac3 files. It has something to do with the p_silence pointer, I'm looking into it
